const firstName = "Jaffar"
export const age = 20
export const courses = ["html", "css", "js"]

export default firstName
// export {  // name export
//     age,
//     courses
// }

// const data = [

//     {
//         "views": 368,
//         "companyName": "Msezy",
//         "featuredBenefits": "Competitive salary, remote work flexibility, exposure to the tourism industry",
//         "skills": [
//             "AdobeCreativeSuiteproficiency",
//             "videoediting",
//             "animation",
//             "motiongraphics",
//             "socialmediadesign",
//             "printdesignexpertise",
//             "typography",
//             "colortheory",
//             "composition",
//             "portfoliodevelopment",
//             "feedbackadaptation",
//             "collaboration",
//             "projectmanagement"
//         ],
//         "category": {
//             "_id": "6499f5ded7d3bec5b121e02b",
//             "name": "Art & Illustration",
//             "description": "Unleash your creativity and join the world of Art and Illustration! This category is perfect for talented artists and visionary illustrators. From traditional techniques to digital wizardry, explore exciting job opportunities where you can bring ideas to life through captivating visuals. Collaborate with various industries and leave a lasting impression with your unique artistic talent. Join us and let your creativity soar in the Art and Illustration category!",
//             "isActive": true,
//             "postCounts": 155,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:32:30.560Z",
//             "updatedAt": "2024-12-18T11:32:55.758Z",
//             "__v": 0
//         },
//         "experience": "2 to 3 Year",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 125000,
//         "payRangeEnd": 150000,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Remote",
//         "jobType": "Full-Time",
//         "_id": "6762b2e7edd2229a87ebf59d",
//         "designation": "Graphic Designer",
//         "desc": "<p><strong>Graphic Designer – Remote</strong></p><p><br></p><p><strong>Working Hours: </strong>11:00 am to 8:00 Pm</p><p><strong>Working Days:</strong> Mon to Fri (Sat Half ay, Sun Off)</p><p><strong>Industry: </strong>Travel &amp; Tourism</p><p><strong>Specialties: </strong>UAE TOURIST VISA SERVICES and WORLDWIDE HOTEL RESERVATIONS</p><p><br></p><p><strong>Job Summary:</strong></p><p><br></p><p>We are seeking a highly creative and talented Graphic Designer to join our marketing team. The ideal candidate should have a keen eye for design, expertise in Adobe Creative Suite, and a passion for storytelling through visuals. This role focuses on video editing, social media content creation, and print design, contributing to the promotion of our Tourism’s brand, products, and services.</p><p><br></p><p><strong>Key Responsibilities:</strong></p><p><br></p><ul><li><strong>Creative Design:</strong> Develop visually appealing materials for social media, websites, advertisements, brochures, and marketing campaigns.</li><li><strong>Video Production:</strong> Create and edit high-quality video content for social media platforms and promotional purposes.</li><li><strong>Social Media Content:</strong> Design engaging visuals tailored to platforms like Instagram, Facebook, LinkedIn, and Twitter to increase engagement and brand awareness.</li><li><strong>Print Materials: </strong>Design print assets such as flyers, brochures, posters, business cards, and banners for the company and its clients.</li><li><strong>Brand Alignment:</strong> Ensure all visual materials are consistent with the company’s branding guidelines.</li><li><strong>Collaboration: </strong>Work with marketing and other departments to align on project goals and design needs.</li><li><strong>Creative Input: </strong>Contribute ideas during brainstorming sessions for marketing initiatives and campaigns.</li><li><strong>Feedback Implementation:</strong> Adapt designs based on feedback to meet management and client expectations.</li></ul><p><br></p><p><strong>Skills &amp; Qualifications:</strong></p><p><br></p><ul><li>Proficiency in Adobe Creative Suite (Illustrator, Photoshop, InDesign, Premiere Pro, After Effects).</li><li>Expertise in video editing, animation, and motion graphics.</li><li>Knowledge of social media platforms and creating tailored content for them.</li><li>Strong understanding of design principles, including typography, color theory, and composition.</li><li>Experience in print production and preparing files for professional printing.</li><li>Ability to manage multiple projects, meet deadlines, and adapt to feedback.</li><li>A comprehensive portfolio showcasing expertise in digital and print designs, social media visuals, and video content.</li><li>Excellent communication skills and experience working collaboratively.</li><li>Bachelor’s degree in Graphic Design, Visual Arts, or a related field (preferred but not mandatory).</li></ul><p><br></p><p><strong>Preferred Qualifications:</strong></p><p><br></p><ul><li>2 to 3 Years of Experience in the tourism or hospitality industry as a graphic designer.</li><li>Proficiency in motion graphics and additional video editing tools.</li></ul><p><br></p><p><strong>Skills</strong></p><ul><li>Adobe Creative Suite proficiency</li><li>Video Editing &amp; Production</li><li>Social Media Design Knowledge</li><li>Print Design Expertise</li><li>Portfolio development</li><li>Motion Graphics Expertise</li></ul><p><br></p><p><strong>Job Detail</strong></p><p><strong>Experience:</strong> 2 Years - 3 Years</p><p><strong>Salary: </strong>Rs. 125,000 - 150,000</p><p><br></p><p>share your resume at <a href=\"mailto:hr@msezy.com\" rel=\"noopener noreferrer\" target=\"_blank\">hr@msezy.com</a></p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "graphicdesign",
//             "remotejobs",
//             "tourismindustry",
//             "AdobeCreativeSuite",
//             "videoediting",
//             "motiongraphics",
//             "socialmediadesign",
//             "printdesign",
//             "creativejobs",
//             "branding",
//             "digitalmarketing",
//             "travelandtourism",
//             "jobopportunity",
//             "full-timeremotejob",
//             "designexpertise",
//             "portfoliodevelopment",
//             "professionalprinting",
//             "creativeteamcollaboration"
//         ],
//         "country": "",
//         "city": "",
//         "isActive": true,
//         "createdAt": "2024-12-18T11:32:55.663Z",
//         "updatedAt": "2024-12-18T16:14:51.660Z",
//         "gender": "",
//         "applyEmail": "hr@msezy.com",
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 10,
//         "companyName": "",
//         "featuredBenefits": "Instant payment upon verification and purchase",
//         "skills": [
//             "GooglePlayConsole",
//             "Accounttrading",
//             "Digitalplatforms",
//             "Accountmanagement",
//             "Onlinetransactions",
//             "Verificationprocess",
//             "Communication"
//         ],
//         "category": {
//             "_id": "6499f691d7d3bec5b121e037",
//             "name": "Information Tech",
//             "description": "Join the cutting-edge field of Information Tech! This category is perfect for tech enthusiasts who excel in areas such as software engineering, cybersecurity, and data analysis. Whether you're a programmer, a network administrator, or a data scientist, find exciting opportunities to contribute to technological advancements. Join us and shape the future of IT!",
//             "isActive": true,
//             "postCounts": 75,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:35:29.119Z",
//             "updatedAt": "2024-12-18T08:34:37.196Z",
//             "__v": 0
//         },
//         "experience": "",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 200,
//         "payRangeEnd": 400,
//         "salaryCurrency": "USD",
//         "jobFeseability": "Remote",
//         "jobType": "Contract",
//         "_id": "6762891dedd2229a87ebf355",
//         "designation": "Google Play Console Account Buyer",
//         "desc": "<p>I wanted to purchase Google Play Console Account created before 2023 November.</p><p><br></p><p>If anyone selling please contact with me as I wanted to buy.</p><p><br></p><p><strong>Budget: </strong>200-400$</p><p><strong>Contact: </strong>+923364771899 (Whatsapp)</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "GooglePlayConsole",
//             "accounttrading",
//             "onlineservices",
//             "digitalplatforms",
//             "remotework",
//             "freelancejob",
//             "onlinebuying",
//             "digitalaccounts",
//             "techservices",
//             "globaljobs",
//             "buyandsell",
//             "accountmanagement",
//             "Googleaccounts"
//         ],
//         "country": "",
//         "city": "",
//         "isActive": true,
//         "createdAt": "2024-12-18T08:34:37.116Z",
//         "updatedAt": "2024-12-18T15:49:53.352Z",
//         "gender": "",
//         "applyEmail": "",
//         "applyPhone": 923364771899,
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 15,
//         "companyName": "SNJ Global Services",
//         "featuredBenefits": "Opportunity to work in a dynamic environment",
//         "skills": [
//             "Coldcalling",
//             "Communicationskills",
//             "Customerhandling",
//             "Telemarketing",
//             "Sales",
//             "Persuasion",
//             "Negotiation",
//             "Customerservice",
//             "Leadgeneration",
//             "Callcenteroperations"
//         ],
//         "category": {
//             "_id": "6499f660d7d3bec5b121e02f",
//             "name": "Marketing & Sales",
//             "description": "Explore exciting opportunities in Marketing & Sales! This category is perfect for professionals who excel in creating impactful strategies and driving business growth. From digital marketing to brand management, find your perfect role and make a measurable impact in this dynamic field. Join us and unleash your marketing and sales expertise!",
//             "isActive": true,
//             "postCounts": 570,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:34:40.106Z",
//             "updatedAt": "2024-12-18T08:28:12.724Z",
//             "__v": 0
//         },
//         "experience": "",
//         "position": "Mid-Level",
//         "noOfPositions": 2,
//         "payRangeStart": 0,
//         "payRangeEnd": 0,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Onsite",
//         "jobType": "Full-Time",
//         "_id": "6762879cedd2229a87ebf214",
//         "designation": "Cold Calling Agent",
//         "desc": "<p>🌟 We Are Hiring <strong>Cold Calling Agents</strong>! 🌟</p><p><br></p><p>Join <strong>SNJ Global Services </strong>and become a part of our dynamic team!</p><p><br></p><p><strong>📍 Location:</strong> Tariq Road, Karachi</p><p><strong>🕒 Shift Timings:</strong> 7:00 PM to 4:00 AM (Night Shift)</p><p><strong>📅 Work Days:</strong> Monday to Saturday</p><p><strong>💼 Job Type:</strong> On-site</p><p><br></p><p>If you have excellent communication skills and are ready to excel in the cold-calling field, we want to hear from you!</p><p><br></p><p><strong>📧 Apply Now: </strong><a href=\"mailto:hr.snjglobal@gmail.com\" rel=\"noopener noreferrer\" target=\"_blank\">hr.snjglobal@gmail.com</a></p><p>Or WhatsApp us at <strong>03327906544</strong></p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "coldcallingagent",
//             "communicationskills",
//             "customerservice",
//             "telemarketing",
//             "salesjobs",
//             "leadgeneration",
//             "customerhandling",
//             "nightshift",
//             "on-sitejobs",
//             "Karachijobs",
//             "hiringnow",
//             "full-timejobs",
//             "SNJGlobalServices",
//             "callcenterjobs",
//             "dynamicenvironment"
//         ],
//         "country": "Pakistan",
//         "city": "Karachi",
//         "isActive": true,
//         "createdAt": "2024-12-18T08:28:12.595Z",
//         "updatedAt": "2024-12-18T16:09:47.178Z",
//         "gender": "",
//         "applyEmail": "hr.snjglobal@gmail.com",
//         "applyPhone": 3327906544,
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 98,
//         "companyName": "Onscreen Solution",
//         "featuredBenefits": "Competitive salary, night shift flexibility, opportunity to work on exciting projects",
//         "skills": [
//             "Animationprinciples",
//             "Characteranimation",
//             "Facialanimation",
//             "Maya",
//             "Blender",
//             "Timing",
//             "Weight",
//             "Motionfluidity",
//             "Objectanimation",
//             "Animationportfolio"
//         ],
//         "category": {
//             "_id": "651ee269964831af97354d74",
//             "name": "Animation",
//             "description": "3d and 2d Animation and Motion Graphics Artist",
//             "isActive": true,
//             "postCounts": 90,
//             "createdBy": "651edd68cff4b74735bb3fd4",
//             "createdAt": "2023-10-05T16:20:57.994Z",
//             "updatedAt": "2024-12-17T08:42:36.702Z",
//             "__v": 0
//         },
//         "experience": " to  Year",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 0,
//         "payRangeEnd": 0,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Onsite",
//         "jobType": "Full-Time",
//         "_id": "6761397cedd2229a87ebd7d1",
//         "designation": "Animator",
//         "desc": "<p><strong>Job Opportunity: </strong>Animator (Night Shift)&nbsp;&nbsp;</p><p><br></p><p><strong>Location:</strong> On-site (Night Shift)&nbsp;&nbsp;</p><p><strong>Timings: </strong>9pm to 6am&nbsp;</p><p><br></p><p>We’re expanding our team and have openings for position:&nbsp;&nbsp;</p><p><br></p><ul><li>Animator&nbsp;&nbsp;</li></ul><p>&nbsp;&nbsp;</p><p><strong>Responsibilities:&nbsp;&nbsp;</strong></p><ul><li>Bring characters and scenes to life with realistic animations.&nbsp;&nbsp;</li><li>Work on character motion, facial expressions, and object animations.&nbsp;&nbsp;</li><li>Collaborate closely with the modelling and rigging team.</li></ul><p><br></p><p><strong>Requirements:&nbsp;&nbsp;</strong></p><ul><li>Expertise in animation principles and software such as Maya or Blender.&nbsp;&nbsp;</li><li>Strong understanding of timing, weight, and fluidity in animations.&nbsp;&nbsp;</li><li>Portfolio showcasing previous animation work.</li></ul><p><br></p><p><strong>&nbsp;What We Offer:&nbsp;&nbsp;</strong></p><ul><li>Competitive salary aligned with industry standards.&nbsp;&nbsp;</li><li>Night shift flexibility.&nbsp;&nbsp;</li><li>Opportunity to work on innovative and exciting projects.&nbsp;&nbsp;</li></ul><p><br></p><p><strong>Apply Now!&nbsp;&nbsp;</strong></p><p>Send your portfolio and CV to <a href=\"mailto:amad@onscreensolution.co\" rel=\"noopener noreferrer\" target=\"_blank\">amad@onscreensolution.co</a></p><p>Join a creative and dynamic team that values excellence!</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "animator",
//             "animationjobs",
//             "Maya",
//             "Blender",
//             "characteranimation",
//             "motiondesign",
//             "animationprinciples",
//             "nightshiftjobs",
//             "full-time",
//             "on-sitejob",
//             "creativeteam",
//             "industrystandards",
//             "hiringanimator",
//             "animationwork",
//             "excitingprojects"
//         ],
//         "country": "",
//         "city": "",
//         "isActive": true,
//         "createdAt": "2024-12-17T08:42:36.621Z",
//         "updatedAt": "2024-12-18T15:07:27.658Z",
//         "gender": "",
//         "applyEmail": "amad@onscreensolution.co",
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 40,
//         "companyName": "Onscreen Solution",
//         "featuredBenefits": "Competitive salary, night shift flexibility, opportunity to work on innovative projects",
//         "skills": [
//             "3Dmodeling",
//             "Rigging",
//             "Maya",
//             "3dsMax",
//             "ZBrush",
//             "Topology",
//             "Deformation",
//             "Workflowoptimization",
//             "Problem-solving",
//             "Attentiontodetail"
//         ],
//         "category": {
//             "_id": "6499f5ded7d3bec5b121e02b",
//             "name": "Art & Illustration",
//             "description": "Unleash your creativity and join the world of Art and Illustration! This category is perfect for talented artists and visionary illustrators. From traditional techniques to digital wizardry, explore exciting job opportunities where you can bring ideas to life through captivating visuals. Collaborate with various industries and leave a lasting impression with your unique artistic talent. Join us and let your creativity soar in the Art and Illustration category!",
//             "isActive": true,
//             "postCounts": 155,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:32:30.560Z",
//             "updatedAt": "2024-12-18T11:32:55.758Z",
//             "__v": 0
//         },
//         "experience": " to  Year",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 0,
//         "payRangeEnd": 0,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Onsite",
//         "jobType": "Full-Time",
//         "_id": "676138dfedd2229a87ebd782",
//         "designation": "Modeller & Rigger",
//         "desc": "<p><strong>Job Opportunity:</strong> Modeller &amp; Rigger (Night Shift)&nbsp;&nbsp;</p><p><br></p><p><strong>Location: </strong>On-site (Night Shift)&nbsp;&nbsp;</p><p><strong>Timings: </strong>9pm to 6am&nbsp;</p><p><br></p><p>We’re expanding our team and have openings for position:&nbsp;&nbsp;</p><p><br></p><ul><li>Modeller &amp; Rigger&nbsp;&nbsp;</li></ul><p>&nbsp;&nbsp;</p><p><strong>Responsibilities:&nbsp;&nbsp;</strong></p><ul><li>Create high-quality 3D models of characters, props, and environments.&nbsp;&nbsp;</li><li>Rig models for seamless animation and efficient workflow.&nbsp;&nbsp;</li><li>Collaborate with the animation team to meet project needs.&nbsp;&nbsp;</li></ul><p><br></p><p><strong>Requirements:&nbsp;&nbsp;</strong></p><ul><li>Proficiency in software like Maya, max, zbrush or similar.&nbsp;&nbsp;</li><li>Strong understanding of topology, rigging, and deformation.&nbsp;&nbsp;</li><li>Attention to detail and problem-solving skills.&nbsp;&nbsp;</li></ul><p><br></p><p><strong>&nbsp;What We Offer:&nbsp;&nbsp;</strong></p><ul><li>Competitive salary aligned with industry standards.&nbsp;&nbsp;</li><li>Night shift flexibility.&nbsp;&nbsp;</li><li>Opportunity to work on innovative and exciting projects.&nbsp;&nbsp;</li></ul><p><br></p><p><strong>Apply Now!&nbsp;&nbsp;</strong></p><p>Send your portfolio and CV to <a href=\"mailto:amad@onscreensolution.co\" rel=\"noopener noreferrer\" target=\"_blank\">amad@onscreensolution.co</a></p><p>Join a creative and dynamic team that values excellence!</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "3Dmodelling",
//             "rigging",
//             "Maya",
//             "3dsMax",
//             "ZBrush",
//             "topology",
//             "deformation",
//             "animationpipeline",
//             "3Dartist",
//             "nightshiftjobs",
//             "creativeteam",
//             "full-timejobs",
//             "on-sitejob",
//             "modellerrigger",
//             "industrystandards",
//             "hiringnow"
//         ],
//         "country": "",
//         "city": "",
//         "isActive": true,
//         "createdAt": "2024-12-17T08:39:59.277Z",
//         "updatedAt": "2024-12-18T14:48:15.978Z",
//         "gender": "",
//         "applyEmail": "amad@onscreensolution.co",
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 31,
//         "companyName": "FMCG Distribution",
//         "featuredBenefits": "Initial training, market-competitive salary",
//         "skills": [
//             "Computerproficiency",
//             "Onlinesalessoftwareknowledge",
//             "Logicalsoftwareunderstanding",
//             "MicrosoftExcel",
//             "Basicformulas",
//             "SAP",
//             "SalesFlo",
//             "SnDPro",
//             "Pace",
//             "Ownconveyance",
//             "Datamanagement"
//         ],
//         "category": {
//             "_id": "6499f691d7d3bec5b121e037",
//             "name": "Information Tech",
//             "description": "Join the cutting-edge field of Information Tech! This category is perfect for tech enthusiasts who excel in areas such as software engineering, cybersecurity, and data analysis. Whether you're a programmer, a network administrator, or a data scientist, find exciting opportunities to contribute to technological advancements. Join us and shape the future of IT!",
//             "isActive": true,
//             "postCounts": 75,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:35:29.119Z",
//             "updatedAt": "2024-12-18T08:34:37.196Z",
//             "__v": 0
//         },
//         "experience": "",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 0,
//         "payRangeEnd": 0,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Onsite",
//         "jobType": "Full-Time",
//         "_id": "6761379dedd2229a87ebd714",
//         "designation": "Key Punching Officer (KPO)",
//         "desc": "<p><strong>Job Description</strong></p><p><br></p><p>A Multi Branches FMCG distribution with vast network in Karachi seeking Services of Key Punching Officer (KPO) for its branches all over Karachi.</p><p><br></p><ul><li>The applicant must be resident of Karachi</li><li>must have proficiency in computer softwares and online Sales Software like (SAP, SalesFlo, SnDPro, Pace. etc)</li><li>must have logical knowledge of how these softwares work.</li><li>must be familiar with Microsoft Excel and basic formulas</li><li>must have own convenience. -</li><li>Market Competitive package will be offered along with initial training.</li></ul><p><br></p><p>Kindly drop your application before 28 Dec. 2024.</p><p><br></p><p><strong>Job Details</strong></p><p>Employment :Full-time</p><p><br></p><p><strong>Drop CV:</strong> 0313 1107869</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "dataentry",
//             "keypunching",
//             "FMCG",
//             "SAP",
//             "SalesFlo",
//             "SnDPro",
//             "Pace",
//             "MicrosoftExcel",
//             "datamanagement",
//             "logicalsoftwareskills",
//             "Karachijobs",
//             "full-time",
//             "on-sitejobs",
//             "jobopportunity",
//             "competitivesalary",
//             "FMCGdistribution"
//         ],
//         "country": "Pakistan",
//         "city": "Karachi",
//         "isActive": true,
//         "createdAt": "2024-12-17T08:34:37.075Z",
//         "updatedAt": "2024-12-18T14:28:50.319Z",
//         "gender": "",
//         "applyEmail": "",
//         "applyPhone": 3131107869,
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 69,
//         "companyName": "",
//         "featuredBenefits": "Paid opportunity, Contribute to helping a visually impaired person, Flexible short-term task",
//         "skills": [
//             "MathematicsExpertise",
//             "PhysicsKnowledge",
//             "ExamAssistance",
//             "AcademicSupport",
//             "SubjectExplanation",
//             "ProblemSolving",
//             "WritingAssistance",
//             "CommunicationSkills",
//             "TimeManagement",
//             "Patience"
//         ],
//         "category": {
//             "_id": "6499f69cd7d3bec5b121e039",
//             "name": "Education",
//             "description": "Make a difference in Education! This category is tailored for passionate educators and professionals in the field of education. From teaching roles to curriculum development, find opportunities to inspire learners and contribute to educational excellence. Join us and become a part of shaping the next generation!",
//             "isActive": true,
//             "postCounts": 37,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:35:40.031Z",
//             "updatedAt": "2024-12-16T16:09:06.511Z",
//             "__v": 0
//         },
//         "experience": "",
//         "position": "Mid-Level",
//         "noOfPositions": 0,
//         "payRangeStart": 0,
//         "payRangeEnd": 0,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Remote",
//         "jobType": "Full-Time",
//         "_id": "676050a2edd2229a87ebcaaa",
//         "designation": "Academic Exam Assistant (Writter)",
//         "desc": "<p>Need a writer</p><p><br></p><p>is there anyone who is expert in maths and physics and completed intermediate from pre- engineering recently and didn't continue university.</p><p><br></p><p>If you are from Karachi then DM me at (whatsApp)&nbsp;<strong>03171206677</strong></p><p><br></p><p>It is a paid task to help visual impaired person in the exam.</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "Hiring",
//             "Karachi",
//             "Maths",
//             "Physics",
//             "Pre-Engineering",
//             "AcademicSupport",
//             "PaidTask",
//             "ExamHelp",
//             "ShortTermJob",
//             "FlexibleWork",
//             "IntermediateStudents",
//             "Education",
//             "Assistance",
//             "VisualImpairmentSupport"
//         ],
//         "country": "Pakistan",
//         "city": "Karachi",
//         "isActive": true,
//         "createdAt": "2024-12-16T16:09:06.418Z",
//         "updatedAt": "2024-12-18T15:12:23.569Z",
//         "gender": "",
//         "applyEmail": "",
//         "applyPhone": 3171206677,
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 56,
//         "companyName": "Codesy Consulting",
//         "featuredBenefits": "Competitive salary, Growth opportunities, Standard benefits package",
//         "skills": [
//             "BusinessDevelopment",
//             "ClientAcquisition",
//             "CommunicationSkills",
//             "SalesStrategies",
//             "LeadGeneration",
//             "ProposalWriting",
//             "NegotiationSkills",
//             "RelationshipManagement",
//             "PresentationSkills",
//             "CRMTools",
//             "MarketResearch",
//             "Goal-Oriented",
//             "InternationalSales",
//             "StrategicPlanning"
//         ],
//         "category": {
//             "_id": "6499f660d7d3bec5b121e02f",
//             "name": "Marketing & Sales",
//             "description": "Explore exciting opportunities in Marketing & Sales! This category is perfect for professionals who excel in creating impactful strategies and driving business growth. From digital marketing to brand management, find your perfect role and make a measurable impact in this dynamic field. Join us and unleash your marketing and sales expertise!",
//             "isActive": true,
//             "postCounts": 570,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:34:40.106Z",
//             "updatedAt": "2024-12-18T08:28:12.724Z",
//             "__v": 0
//         },
//         "experience": "",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 70000,
//         "payRangeEnd": 150000,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Onsite",
//         "jobType": "Full-Time",
//         "_id": "675fff88edd2229a87ebc463",
//         "designation": "Business Development Executive",
//         "desc": "<p>Hiring Alert</p><p>I'm hiring for following position:</p><p><br></p><ul><li>Business Development Executive</li></ul><p><br></p><p><strong>Requirements:</strong></p><p><br></p><ol><li>Excellent communication skills.</li><li>Sound knowledge of Sales/Business Development.</li><li>Proven track record in Sales/Business Development.</li></ol><p><br></p><p>O/A Levels &amp; Fresh Graduates are encouraged to apply.</p><p><br></p><p><strong>Compensation:</strong> 70k - 150k (as per experience &amp; skill set) + Benefits.</p><p><br></p><p><strong>Official Working Days &amp; Timings:</strong></p><p>Monday to Friday, 7PM - 4AM</p><p><strong>Location: </strong>Gulshan e Iqbal, Karachi.</p><p><br></p><p>Interested candidates can share updated resume at:</p><p><a href=\"mailto:arsalan@codesyconsulting.com\" rel=\"noopener noreferrer\" target=\"_blank\">arsalan@codesyconsulting.com</a></p><p><br></p><p>Please share and forward and feel free to refer if you know any relevant resource for above mentioned positions.</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "Hiring",
//             "ApplyNow",
//             "Jobs",
//             "Karachi",
//             "BusinessDevelopment",
//             "Executive",
//             "TechIndustry",
//             "SoftwareHouseJobs",
//             "Sales",
//             "FreshGraduates",
//             "CommunicationSkills",
//             "GrowthOpportunities",
//             "ClientAcquisition",
//             "InternationalJobs"
//         ],
//         "country": "Pakistan",
//         "city": "Karachi",
//         "isActive": true,
//         "createdAt": "2024-12-16T10:23:04.594Z",
//         "updatedAt": "2024-12-18T11:26:31.873Z",
//         "gender": "",
//         "applyEmail": "arsalan@codesyconsulting.com",
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 36,
//         "companyName": "Codesy Consulting",
//         "featuredBenefits": "Competitive salary, Standard benefits package, Opportunity to work in an international environment",
//         "skills": [
//             "CommunicationSkills",
//             "SalesTechniques",
//             "BusinessDevelopment",
//             "LeadGeneration",
//             "ClientManagement",
//             "NegotiationSkills",
//             "PresentationSkills",
//             "CustomerHandling",
//             "RelationshipBuilding",
//             "SalesTargetAchievement",
//             "CRMSoftware",
//             "MarketResearch",
//             "TeamCollaboration"
//         ],
//         "category": {
//             "_id": "6499f660d7d3bec5b121e02f",
//             "name": "Marketing & Sales",
//             "description": "Explore exciting opportunities in Marketing & Sales! This category is perfect for professionals who excel in creating impactful strategies and driving business growth. From digital marketing to brand management, find your perfect role and make a measurable impact in this dynamic field. Join us and unleash your marketing and sales expertise!",
//             "isActive": true,
//             "postCounts": 570,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:34:40.106Z",
//             "updatedAt": "2024-12-18T08:28:12.724Z",
//             "__v": 0
//         },
//         "experience": "",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 70000,
//         "payRangeEnd": 150000,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Onsite",
//         "jobType": "Full-Time",
//         "_id": "675fff0eedd2229a87ebc418",
//         "designation": "Sales Development Representative",
//         "desc": "<p>Hiring Alert</p><p>I'm hiring for following position:</p><p><br></p><ul><li>Sales Development Representative</li></ul><p><br></p><p><strong>Requirements:</strong></p><p><br></p><ol><li>Excellent communication skills.</li><li>Sound knowledge of Sales/Business Development.</li><li>Proven track record in Sales/Business Development.</li></ol><p><br></p><p>O/A Levels &amp; Fresh Graduates are encouraged to apply.</p><p><br></p><p><strong>Compensation:</strong> 70k - 150k (as per experience &amp; skill set) + Benefits.</p><p><br></p><p><strong>Official Working Days &amp; Timings:</strong></p><p>Monday to Friday, 7PM - 4AM</p><p><strong>Location: </strong>Gulshan e Iqbal, Karachi.</p><p><br></p><p>Interested candidates can share updated resume at:</p><p><a href=\"mailto:arsalan@codesyconsulting.com\" rel=\"noopener noreferrer\" target=\"_blank\">arsalan@codesyconsulting.com</a></p><p><br></p><p>Please share and forward and feel free to refer if you know any relevant resource for above mentioned positions.</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "Hiring",
//             "ApplyNow",
//             "Jobs",
//             "Karachi",
//             "Sales",
//             "International",
//             "Representative",
//             "TechIndustry",
//             "BusinessDevelopment",
//             "FreshGraduates",
//             "SoftwareHouseJobs",
//             "ClientManagement",
//             "SalesJobs",
//             "CommunicationSkills"
//         ],
//         "country": "Pakistan",
//         "city": "Karachi",
//         "isActive": true,
//         "createdAt": "2024-12-16T10:21:02.449Z",
//         "updatedAt": "2024-12-18T07:02:15.622Z",
//         "gender": "",
//         "applyEmail": "arsalan@codesyconsulting.com",
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     },
//     {
//         "views": 32,
//         "companyName": "",
//         "featuredBenefits": "Remote work opportunity, Flexible working hours, Collaboration on a trading platform project, Potential for future projects",
//         "skills": [
//             "Python",
//             "APIIntegration",
//             "WebSockets",
//             "TradingBots",
//             "Pump.fun",
//             "AutomationScripts",
//             "Real-timeNotifications",
//             "MobileAlerts",
//             "RESTAPIs",
//             "DataParsing",
//             "AlgorithmDevelopment",
//             "Debugging",
//             "ErrorHandling",
//             "PushNotifications",
//             "TelegramBotDevelopment",
//             "Flask/Django",
//             "CloudIntegration",
//             "ProblemSolving",
//             "SoftwareOptimization"
//         ],
//         "category": {
//             "_id": "6499f66cd7d3bec5b121e031",
//             "name": "Development",
//             "description": "Unlock your potential in Development! This category is tailored for talented professionals who thrive on building innovative solutions and pushing technological boundaries. Whether you specialize in software development, web development, or mobile app development, find your next challenge and contribute to cutting-edge projects. Join us and let your development skills shine!",
//             "isActive": true,
//             "postCounts": 378,
//             "createdBy": "63dea7b3fa1a27096f4ea85a",
//             "createdAt": "2023-06-26T20:34:52.137Z",
//             "updatedAt": "2024-12-16T07:50:52.054Z",
//             "__v": 0
//         },
//         "experience": "2 to 2.5 Year",
//         "position": "Mid-Level",
//         "noOfPositions": 1,
//         "payRangeStart": 0,
//         "payRangeEnd": 0,
//         "salaryCurrency": "PKR",
//         "jobFeseability": "Remote",
//         "jobType": "Contract",
//         "_id": "675fdbdbedd2229a87ebbba2",
//         "designation": "Python Bot Developer",
//         "desc": "<p>Looking for a python bot developer for Pump.fun is a trading platform.</p><p><br></p><p>I need someone to make a bot for this platform. Want notification in mobile.</p><p>If you’re fit for that hit me up for more info.</p><p><br></p><p><strong>WhatsApp:</strong> 03340317756</p>",
//         "isVerified": true,
//         "isHidden": false,
//         "hashTags": [
//             "PythonDeveloper",
//             "BotDeveloper",
//             "TradingBot",
//             "APIIntegration",
//             "Pump.fun",
//             "MobileNotifications",
//             "RemoteJobs",
//             "FreelanceDeveloper",
//             "SoftwareAutomation",
//             "TradingPlatform",
//             "WebSockets",
//             "TechJobs",
//             "PythonProgramming",
//             "NotificationBots",
//             "FreelanceOpportunities",
//             "Real-timeAutomation",
//             "ScriptDevelopment",
//             "MobileAlerts",
//             "TechTalent",
//             "APIDevelopment"
//         ],
//         "country": "",
//         "city": "",
//         "isActive": true,
//         "createdAt": "2024-12-16T07:50:51.971Z",
//         "updatedAt": "2024-12-18T14:37:16.217Z",
//         "gender": "",
//         "applyEmail": "",
//         "applyPhone": 3340317756,
//         "sponsored": false,
//         "user": {
//             "userId": "663681ced78314aa80690e64",
//             "firstName": "Hasan",
//             "lastName": "Ashraf",
//             "userName": "Hasan"
//         }
//     }
// ]

// const age = 18
// const gender = "male"

// export default data //default export

// export { age, gender } //name export